/// <reference types="lodash" />
import Bluebird from 'bluebird';
import CID from 'cids';
import { StatResult } from 'ipfs-core-types/src/files';
export declare const deepEntryListMap: Map<string, string>;
export declare const newEntryListMap: Map<string, string>;
export declare function appendDeepEntryListMapByStatResult(path: string, entry: StatResult): boolean;
export declare function appendDeepEntryListMap(path: string, cid: string | CID | StatResult["cid"], isDirectory?: boolean): boolean;
export declare function loadDeepEntryListMapFromFile(): Bluebird<Map<string, string>>;
export declare function loadDeepEntryListMapFromServer(): Bluebird<Map<string, string>>;
export declare function loadDeepEntryListMapFromMixin(): Bluebird<Map<string, string>>;
export declare function _saveDeepEntryListMapToServer(): Bluebird<Map<string, string>>;
export declare function enableForceSave(): void;
export declare function enableOverwriteServer(): void;
export declare function _saveDeepEntryListMapToFile(): Bluebird<Map<string, string>>;
export declare const saveDeepEntryListMapToFile: import("lodash").DebouncedFunc<typeof _saveDeepEntryListMapToFile>;
export declare const saveDeepEntryListMapToServer: import("lodash").DebouncedFunc<typeof _saveDeepEntryListMapToServer>;
export declare function saveDeepEntryListMapToMixin(): Bluebird<Map<string, string>>;
export declare function mergeDeepEntryListMap(input: Map<string, string> | [string, string][], target: Map<string, string>, keepExists?: boolean): Map<string, string>;
export declare function fixDeepEntryListMap(deepEntryListMap: Map<string, string>): Map<string, string>;
