on:
  workflow_dispatch:
  schedule:
    -
      cron: '0 0 5 * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: tbvjaos510/empty-commit-action@0.0.2
      - with:
          token: ${{ secrets.GITHUB_TOKEN }}
          email: action@github.com
          name: GitHub Action
          message: "ci: dummy commit"
