on:
  workflow_dispatch:
  schedule:
    -
      cron: '0 0 5,20 * *'
jobs:
  main-action:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@main
        with:
          fetch-depth: 2
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}
      -
        name: setup git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      -
        name: setup git config
        run: |
          git commit --allow-empty -m 'ci(dummy): keep actions alive'
      -
        name: Push changes
        if: success()
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
