on:
  workflow_dispatch:
  schedule:
    -
      cron: '0 0 5 * *'
jobs:
  uses: velocibear/create-empty-commit@v1.0.0
  with:
    token: ${{ secrets.GITHUB_TOKEN }}
    email: action@github.com
    name: GitHub Action
    message: "ci: dummy commit"
