on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  poke:
    runs-on: ubuntu-latest
#    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 18.12.1
      - name: get yarn cache dir
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: set cache id
        id: id-cache
        run: echo "::set-output name=id::${GITHUB_SHA}"
      - name: echo var
        run: |
          echo ${{ steps.yarn-cache.outputs.dir }}
          echo ${{ steps.id-cache.outputs.id }}
          echo ${GITHUB_SHA}
      - name: yarn cache
        uses: bluelovers/github-actions-cache@2020011001
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ steps.id-cache.outputs.id }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: install deps
        run: |
          yarn run ci:install
      - name: run
        run: |
          yarn run ci:run:poke-all-cache-cid
  
